# Generated by Django 3.1.4 on 2022-03-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount_in_stock', models.DecimalField(decimal_places=0, max_digits=6)),
                ('list_of_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listofproducts')),
            ],
        ),
    ]
