# Generated by Django 3.1.4 on 2022-03-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='list_of_products',
            new_name='listofproducts',
        ),
    ]
