# Generated by Django 3.1.4 on 2022-03-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220313_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='text',
        ),
    ]

