# Generated by Django 3.1.4 on 2022-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220404_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edit_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
