# Generated by Django 3.1.4 on 2022-04-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_book_edit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edit_status',
            field=models.BooleanField(null=True),
        ),
    ]
